### PR TITLE
Hotfix all issues and implement pull request features

### LINKED ISSUE #27: Save to history when opening a file
I usually do not save a new file I downloaded from somewhere before starting to work on it. That way the first time it shows up in Local History is when I save it for the first time. I'd appreciate Local History saving a snapshot when opening a file, too.

I believe you could do it the same way you're already doing it when saving a file. That way it wouldn't save a snapshot of the file when it is being opened and there's a copy of it in Local History already and no changes could be found.

### PR DESCRIPTION
**Pull request by jrappen**
* fixes #27, #30, #39, #40, #50, #52, #53, #55, #56, #58, #59

/cc @vishr

### CODE REVIEW

**Comment by jrappen** [comment]
Feel free to [squash the merge](https://help.github.com/articles/about-pull-request-merge-squashing).

Squash the merge

**Comment by vishr** [comment]
@jrappen Thanks for the PR.

Few points:

- Can we drop spaces between file names? Some OS doesn't like them.
- Have you tested it cross platform? It is the biggest challenge.

~vishal

**Comment by jrappen** [comment]
* [x] drop spaces between file names
  * package itself still has a space in the name
* [ ] test on multiple platforms
  * [x] Windows (10 Pro x64)
  * [ ] Mac
  * [ ] Linux

**Comment by jrappen** [comment]
Could you test this PR? I've been trying to fix almost all remaining issues and merge features from open pull requests. Windows seems alright for me. Need testing on Mac and Linux.

/cc @StoyanDimitrov, @revintec, @slene, @cryptid11, @3v1n0, @imyzf, @primitives, @rwatts3, @astyagun, @unphased

**Comment by jrappen** [comment]
Opening a read-only version of the default settings doesn't currently work. Working on a fix ...

**Comment by vishr** [comment]
@jrappen I am counting on you incase any bug arises ;)

**Pull request merged**
