### PR TITLE
Fixes browsing history on Linux

### PR DESCRIPTION
**Pull request by rhamzeh**
This should fix vishr/local-history#80

### CODE REVIEW

**Comment by jrappen** [comment]
browsing through http://stackoverflow.com/search?q=[python]+xdg-open this looks fine

**Comment by rhamzeh** [comment]
@jrappen I think you need to pass shell=True as the second parameter:
````python
subprocess.call('xdg-open %s' % target_dir, shell=True)
````

I just tried it locally, and this works

**Comment by rhamzeh** [comment]
I was reading more about this in the [python documentation](https://docs.python.org/2/library/subprocess.html#subprocess.Popen):

> "On Unix, if args is a string, the string is interpreted as the name or path of the program to execute"

It seems like if passed a string Popen treats it as if it where the file. That's why if Shell=true this string is passed to bash/sh which will handle the string correctly.

> "the program to execute is the first item in args if args is a sequence."

That's why passing an array works, it launches the program, and passes the rest as arguments to that program.


The page also warns that:

> "Warning Passing shell=True can be a security hazard if combined with untrusted input"
 
but I don't think that's an issue here.

**Comment by jrappen** [comment]
@rhamzeh well why don't you change the line in your PR so @vishr can merge it?

**Pull request merged**
